export const SET_APP_DATA = 'SET_APP_DATA';
export const APP_DATA_LOADING = 'APP_DATA_LOADING';
export const APP_DATA_FAILED = 'APP_DATA_FAILED';

export const SET_USER_DATA = 'SET_USER_DATA';
export const USER_DATA_LOADING = 'USER_DATA_LOADING';
export const USER_DATA_FAILED = 'USER_DATA_FAILED';
export const DELETE_USER_DATA = 'DELETE_USER_DATA';
export const RESET_USER_ERROR = 'RESET_USER_ERROR';


export const SET_LOADING_STATE = "SET_LOADING_STATE";

export const ACTION_MOMENT = "ACTION_MOMENT";
