export const SET_APP_DATA = 'SET_APP_DATA';
export const APP_DATA_LOADING = 'APP_DATA_LOADING';
export const APP_DATA_FAILED = 'APP_DATA_FAILED';

export const SET_USER_DATA = 'SET_USER_DATA';
export const USER_DATA_LOADING = 'USER_DATA_LOADING';
export const USER_DATA_FAILED = 'USER_DATA_FAILED';
export const DELETE_USER_DATA = 'DELETE_USER_DATA';
export const RESET_USER_ERROR = 'RESET_USER_ERROR';

export const SET_IDEAS = 'SET_IDEAS';
export const IDEAS_LOADING = 'IDEAS_LOADING';
export const IDEAS_FAILED = 'IDEAS_FAILED';
export const CLEAN_IDEAS = 'CLEAN_IDEAS';

export const SET_IDEA = 'SET_IDEA';
export const IDEA_LOADING = 'IDEA_LOADING';
export const IDEA_FAILED = 'IDEA_FAILED';
export const IDEA_SUCCES = 'IDEA_SUCCES';
export const RESET_IDEA = 'RESET_IDEA';
export const RESET_IDEA_SUCCES = 'RESET_IDEA_SUCCES';
export const IDEA_CREATED = 'IDEA_CREATED';

export const SET_COLLABORATORS = 'SET_COLLABORATORS';
export const SET_IDEA_ID = 'SET_IDEA_ID';
export const COLLABORATORS_LOADING = 'COLLABORATORS_LOADING';
export const COLLABORATORS_FAILED = 'COLLABORATORS_FAILED';
export const COLLABORATORS_SUCCES = 'COLLABORATORS_SUCCES';
export const RESET_COLLABORATORS = 'RESET_COLLABORATORS';
export const RESET_COLLABORATORS_SUCCES = 'RESET_COLLABORATORS_SUCCES';

export const SET_CANVAS_COMMENTS = 'SET_CANVAS_COMMENTS';
export const CANVAS_COMMENTS_FAILED = 'CANVAS_COMMENTS_FAILED';
export const CANVAS_COMMENTS_SUCCES = 'CANVAS_COMMENTS_SUCCES';
export const CANVAS_COMMENTS_LOADING = 'CANVAS_COMMENTS_LOADING';
export const RESET_CANVAS_COMMENTS_SUCCES = 'RESET_CANVAS_COMMENTS_SUCCES';

export const SET_LOADING_STATE = "SET_LOADING_STATE";

export const ACTION_MOMENT = "ACTION_MOMENT";
